"""add_phone_to_users

Revision ID: 14acf3f2933b
Revises: 4cf6a5af38a0
Create Date: 2026-05-04 10:30:33.503253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14acf3f2933b'
down_revision = '4cf6a5af38a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
