"""add signature fields to referral model

Revision ID: 22bd997c5c6e
Revises: 955d79abcecd
Create Date: 2026-04-26 15:08:05.931262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22bd997c5c6e'
down_revision = '955d79abcecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('signature_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_signed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_column('is_signed')
        batch_op.drop_column('signature_date')
        batch_op.drop_column('signature')

    # ### end Alembic commands ###
