"""add_number_to_classrooms

Revision ID: 5dbfdd9abcd8
Revises: e6f7a8b9c0d1
Create Date: 2026-04-24 23:34:55.305939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dbfdd9abcd8'
down_revision = 'e6f7a8b9c0d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.drop_column('number')

    # ### end Alembic commands ###
