"""add_can_chat_to_users

Revision ID: 850386fec047
Revises: 5dbfdd9abcd8
Create Date: 2026-04-24 23:40:21.013342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850386fec047'
down_revision = '5dbfdd9abcd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_chat', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('can_chat')

    # ### end Alembic commands ###
