"""expand appointment record fields for clinical documentation

Revision ID: 9210b483980d
Revises: c060c04e560b
Create Date: 2026-04-26 14:55:25.014287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9210b483980d'
down_revision = 'c060c04e560b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_assignment_attachments')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chief_complaint', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('observed_behaviors', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('emotional_state', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('clinical_impression', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('recommendations', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('next_steps', sa.Text(), nullable=True))

    with op.batch_alter_table('assignment_attachments', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_assignment_attachments_assignment_id'))

    with op.batch_alter_table('submission_history_events', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_history_events', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('assignment_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignment_attachments_assignment_id'), ['assignment_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('next_steps')
        batch_op.drop_column('recommendations')
        batch_op.drop_column('clinical_impression')
        batch_op.drop_column('emotional_state')
        batch_op.drop_column('observed_behaviors')
        batch_op.drop_column('chief_complaint')

    op.create_table('_alembic_tmp_assignment_attachments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('assignment_id', sa.INTEGER(), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=255), nullable=False),
    sa.Column('original_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
