"""add referral model for psychologist encaminhamentos

Revision ID: 955d79abcecd
Revises: 9210b483980d
Create Date: 2026-04-26 15:01:12.488001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955d79abcecd'
down_revision = '9210b483980d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('referral_type', sa.String(length=50), nullable=False),
    sa.Column('professional_name', sa.String(length=120), nullable=True),
    sa.Column('institution', sa.String(length=200), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('referral_date', sa.DateTime(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('psychologist_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['psychologist_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referrals_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referrals_psychologist_id'), ['psychologist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referrals_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referrals_student_id'))
        batch_op.drop_index(batch_op.f('ix_referrals_psychologist_id'))
        batch_op.drop_index(batch_op.f('ix_referrals_appointment_id'))

    op.drop_table('referrals')
    # ### end Alembic commands ###
