"""phone_not_null

Revision ID: dcfd074d30bb
Revises: 14acf3f2933b
Create Date: 2026-05-04 10:33:29.038103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcfd074d30bb'
down_revision = '14acf3f2933b'
branch_labels = None
depends_on = None


def upgrade():
    # Preenche registros com phone NULL antes de impor NOT NULL
    op.execute("UPDATE users SET phone = '' WHERE phone IS NULL")

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
